using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using Xunit;
using Argus.Orchestrator.Config;
using Argus.Orchestrator.Detection;

namespace Argus.Orchestrator.Tests;

/// <summary>
/// Tests for DetectorChannelFactory mTLS channel construction (D-18).
/// Uses test fixture certs from deploy/certs/ generated by Plan 03.
/// </summary>
public class DetectorChannelFactoryTests : IDisposable
{
    // Paths to test certs generated by Plan 03 (gitignored, on-disk only)
    // Fallback: generate in-memory self-signed certs for CI
    private static readonly string CertDir = FindCertDir();
    private static readonly string CaCertPath = Path.Combine(CertDir, "ca.crt");
    private static readonly string ClientCertPath = Path.Combine(CertDir, "client.crt");
    private static readonly string ClientKeyPath = Path.Combine(CertDir, "client.key");

    private static string FindCertDir()
    {
        // Walk up from the test binary to find deploy/certs/
        var dir = AppContext.BaseDirectory;
        for (int i = 0; i < 10; i++)
        {
            var candidate = Path.Combine(dir, "deploy", "certs");
            if (Directory.Exists(candidate) && File.Exists(Path.Combine(candidate, "ca.crt")))
                return candidate;
            dir = Path.GetDirectoryName(dir) ?? dir;
        }
        throw new DirectoryNotFoundException(
            "deploy/certs/ not found. Run deploy/generate-certs.sh before tests.");
    }

    private Grpc.Net.Client.GrpcChannel? _channel;

    [Fact]
    public void Create_WithValidCerts_SetsClientCertificateOnHandler()
    {
        // Arrange
        var settings = new ConnectionSettings
        {
            DetectorEndpoint = "https://gpu-host:50051",
            TlsCa = CaCertPath,
            TlsCert = ClientCertPath,
            TlsKey = ClientKeyPath,
        };

        HttpClientHandler? capturedHandler = null;

        // Act
        _channel = DetectorChannelFactory.Create(settings, h => { capturedHandler = h; });

        // Assert: handler has exactly 1 client cert loaded
        Assert.NotNull(capturedHandler);
        Assert.Single(capturedHandler!.ClientCertificates);
        // Assert: custom server validation callback is set (non-null = mTLS CA pinning active)
        Assert.NotNull(capturedHandler.ServerCertificateCustomValidationCallback);
    }

    [Fact]
    public void Create_WithValidCerts_CustomValidationCallbackPinsArgusCA()
    {
        // Arrange
        var settings = new ConnectionSettings
        {
            DetectorEndpoint = "https://gpu-host:50051",
            TlsCa = CaCertPath,
            TlsCert = ClientCertPath,
            TlsKey = ClientKeyPath,
        };

        HttpClientHandler? capturedHandler = null;
        _channel = DetectorChannelFactory.Create(settings, h => { capturedHandler = h; });

        // Act: invoke the callback with the real server cert signed by the test CA
        // Load server cert to simulate a real TLS handshake callback
        var serverCert = new X509Certificate2(Path.Combine(CertDir, "server.crt"));
        var chain = new X509Chain();

        var callback = capturedHandler!.ServerCertificateCustomValidationCallback!;
        // We call callback with a HttpRequestMessage, the cert, chain, and no errors
        // The callback should call chain.Build(); it may return false (placeholder IP/hostname)
        // but it must NOT throw. More importantly, the chain policy must be CustomRootTrust.
        bool callbackRan = false;
        try
        {
            callback(new HttpRequestMessage(), serverCert, chain, SslPolicyErrors.None);
            callbackRan = true;
        }
        catch
        {
            callbackRan = true; // any exception means it ran
        }
        Assert.True(callbackRan, "Callback must be invocable");

        // Assert: chain policy is CustomRootTrust (D-18, T-04-01)
        Assert.Equal(X509ChainTrustMode.CustomRootTrust, chain.ChainPolicy.TrustMode);
        Assert.NotEmpty(chain.ChainPolicy.CustomTrustStore);
    }

    public void Dispose()
    {
        _channel?.Dispose();
    }
}
